name: RPM Packaging

on:
  push:
    branches:
      - master

jobs:
  linux:
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-22.04-arm ]
    name: RPM Packaging
    runs-on: ${{ matrix.os }}
    container: rockylinux:9
    steps:
      - name: Install Dependencies
        run: |
          cat /etc/redhat-release
          yum -y install epel-release
          /usr/bin/crb enable
          yum -y install cairo-devel libpng-devel libjpeg-turbo-devel zlib-devel bzip2-devel swig netpbm netpbm-devel netpbm-progs cfitsio-devel python3-devel python3-numpy python3-rpm-macros rpm-build rpm-sign make systemd-rpm-macros gcc make git

      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Package RPM
        run: make

      - name: Clone Package Repository
        uses: actions/checkout@v4
        with:
          repository: rockit-astro/packages
          token: ${{ secrets.DEPLOY_TOKEN }}
          path: packages

      - name: Push Packages
        env:
          RPM_SIGNING_KEY: ${{ secrets.RPM_SIGNING_KEY }}
        run: |
          packages/sign-and-push-packages.sh *.rpm

